# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{messiah}
  s.version = "0.9.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rich Cavanaugh"]
  s.date = %q{2010-04-14}
  s.default_executable = %q{messiah-generator}
  s.description = %q{Messiah enables using Ruby testing tools for integration testing with platforms that support CGI. Notably, PHP.}
  s.email = %q{rich@withoutscope.com}
  s.executables = ["messiah-generator"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc",
     "TODO"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "TODO",
     "VERSION",
     "bin/messiah-generator",
     "lib/messiah.rb",
     "lib/messiah/config.rb",
     "lib/messiah/configurator.rb",
     "lib/messiah/generator.rb",
     "lib/messiah/generator/application.rb",
     "lib/messiah/generator/cucumber.rb",
     "lib/messiah/generator/options.rb",
     "lib/messiah/generator/rspec.rb",
     "lib/messiah/generator/test_unit.rb",
     "lib/messiah/rack.rb",
     "lib/messiah/rack/cgi.rb",
     "lib/messiah/supports/code_igniter.php",
     "lib/messiah/supports/code_igniter.rb",
     "lib/messiah/supports/common.rb",
     "lib/messiah/supports/cucumber.rb",
     "lib/messiah/supports/rspec.rb",
     "lib/messiah/supports/test_unit.rb",
     "lib/messiah/templates/cucumber/features/messiah.feature",
     "lib/messiah/templates/cucumber/features/step_definitions/web_steps.rb",
     "lib/messiah/templates/cucumber/features/support/env.rb",
     "lib/messiah/templates/cucumber/features/support/paths.rb",
     "lib/messiah/templates/rspec/spec/spec_helper.rbt",
     "spec/fixtures/www/another.php",
     "spec/fixtures/www/destination.php",
     "spec/fixtures/www/env.php",
     "spec/fixtures/www/form.php",
     "spec/fixtures/www/get_vars.php",
     "spec/fixtures/www/index.php",
     "spec/fixtures/www/path_info.php",
     "spec/fixtures/www/process.php",
     "spec/fixtures/www/redirector.php",
     "spec/fixtures/www/uploaded.php",
     "spec/fixtures/www/uploader.php",
     "spec/messiah_config_spec.rb",
     "spec/messiah_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/rich/messiah}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{The beauty of Ruby integration tests for PHP}
  s.test_files = [
    "spec/messiah_config_spec.rb",
     "spec/messiah_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<webrat>, [">= 0"])
      s.add_runtime_dependency(%q<rack>, [">= 0"])
      s.add_runtime_dependency(%q<rack-test>, [">= 0"])
      s.add_runtime_dependency(%q<activerecord>, [">= 0"])
      s.add_runtime_dependency(%q<factory_girl>, [">= 0"])
      s.add_runtime_dependency(%q<dr_nic_magic_models>, [">= 0"])
      s.add_runtime_dependency(%q<database_cleaner>, [">= 0"])
    else
      s.add_dependency(%q<webrat>, [">= 0"])
      s.add_dependency(%q<rack>, [">= 0"])
      s.add_dependency(%q<rack-test>, [">= 0"])
      s.add_dependency(%q<activerecord>, [">= 0"])
      s.add_dependency(%q<factory_girl>, [">= 0"])
      s.add_dependency(%q<dr_nic_magic_models>, [">= 0"])
      s.add_dependency(%q<database_cleaner>, [">= 0"])
    end
  else
    s.add_dependency(%q<webrat>, [">= 0"])
    s.add_dependency(%q<rack>, [">= 0"])
    s.add_dependency(%q<rack-test>, [">= 0"])
    s.add_dependency(%q<activerecord>, [">= 0"])
    s.add_dependency(%q<factory_girl>, [">= 0"])
    s.add_dependency(%q<dr_nic_magic_models>, [">= 0"])
    s.add_dependency(%q<database_cleaner>, [">= 0"])
  end
end

